name: untitled4
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  # 알람 기능을 위한 패키지들 추가
  audioplayers: ^5.2.1        # 소리 재생용
  haptic_feedback: ^0.4.2     # 진동 효과용 (vibration 대체)
  permission_handler: ^11.1.0  # 권한 관리용
  wakelock_plus: ^1.2.1       # 화면 켜짐 유지용
  flutter_local_notifications: ^17.2.2  # 로컬 알림용
  flutter_web_auth_2: ^4.1.0  # OAuth 인증 (migrated)
  crypto: ^3.0.1  # PKCE 생성
  flutter_dotenv: ^5.0.2  # 환경변수 관리
  add_2_calendar: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets 부분 수정 - assets 폴더와 .env 등록 (폴더 및 .env 파일이 생성되어 있어야 함)
  assets:
    - .env
    - assets/images/
    - assets/sounds/  # 알람 소리 파일용 (선택사항)
    - assets/signin-assets/  # 로그인 아이콘 등 추가 자산